CREATE TABLE user 
(
	id INT AUTO_INCREMENT NOT NULL, 
	Name VARCHAR(30) NOT NULL, 
	Password VARCHAR(100) NOT NULL, 
	Email VARCHAR(50) NOT NULL UNIQUE, 
	Phone VARCHAR(20) DEFAULT NULL, 
	PRIMARY KEY(id)
) 
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;